### ISSUE TITLE
GHA workflow for deploying our website takes down our docs

### ISSUE THREAD

**Issue by jlewi** [jlewi/roboweb-docs#10]
Everytime the GHA action for our docs runs it ends up unsetting the custom domain for our webpage and we end up getting a 404 on our docs.

**Comment by jlewi** [comment]
<img width="1728" alt="Screen Shot 2023-04-09 at 11 19 57 AM" src="https://user-images.githubusercontent.com/777219/230789817-30b1e6a6-2702-475a-bda8-ee657494494c.png">

Setting the custom domain back to `www.roboweb.app` appears to fix it.

**Comment by hamelsmu** [comment]
I fixed this in #12 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/1483922/230798790-f6dc494b-8deb-4d01-80c5-d204d2e7f065.png">
